name: Gerar conteúdo automático

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Instalar dependências Python
      run: |
        pip install fpdf

    - name: Executar script Python
      run: python gerar_conteudo.py

    - name: Commit e push (bot)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Novo conteúdo gerado automaticamente" || echo "Sem alterações"
        git push
